/* parser generated by jison 0.4.17 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var elementos = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,5],$V1=[1,7],$V2=[1,12],$V3=[5,8,47],$V4=[8,47],$V5=[1,18],$V6=[1,29],$V7=[1,31],$V8=[1,30],$V9=[1,32],$Va=[15,16],$Vb=[5,8,19,25,29,30,32,33,44,47],$Vc=[19,25,30,32,33,44],$Vd=[1,63],$Ve=[1,69],$Vf=[1,70],$Vg=[15,16,19,25,30,32,33,41,42,44],$Vh=[15,16,19,25,30,32,33,44];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"start":3,"procedures":4,"EOF":5,"procedure":6,"coments":7,"comentario":8,"identifier":9,":":10,"block":11,"params":12,"{":13,"paramNames":14,"}":15,",":16,"Inicio":17,"statements":18,"Fin":19,"statement":20,"conditional":21,"invocation":22,"repeat":23,"action":24,"Si":25,"ifCond":26,"Entonces":27,"optElse":28,"Sino":29,"(":30,"condition":31,")":32,"[":33,"]":34,"arguments":35,"argNames":36,"argName":37,"aritmetic":38,"rIndex":39,"literal":40,"+":41,"-":42,"numeric":43,"ACTION":44,"condicion":45,"no":46,"IDENTIFIER":47,"NUMERIC":48,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",8:"comentario",10:":",13:"{",15:"}",16:",",17:"Inicio",19:"Fin",25:"Si",27:"Entonces",29:"Sino",30:"(",32:")",33:"[",34:"]",41:"+",42:"-",44:"ACTION",45:"condicion",46:"no",47:"IDENTIFIER",48:"NUMERIC"},
productions_: [0,[3,2],[4,2],[4,3],[4,2],[4,1],[7,2],[7,1],[6,3],[6,4],[12,3],[14,3],[14,1],[11,3],[11,2],[18,2],[18,1],[20,1],[20,1],[20,1],[20,1],[21,5],[28,0],[28,2],[26,3],[22,3],[22,4],[35,3],[36,3],[36,1],[37,3],[23,4],[39,1],[38,1],[38,3],[38,3],[40,1],[40,1],[24,1],[31,1],[31,2],[9,1],[43,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
return mkArray($$[$0-1]);
break;
case 2: case 6: case 15:
this.$ = merge($$[$0-1], $$[$0]);
break;
case 3:
this.$ = merge($$[$0-2], add_comments($$[$0], $$[$0-1]));
break;
case 4:
this.$ = add_comments($$[$0], $$[$0-1]);
break;
case 7:
this.$ = mkArray($$[$0]);
break;
case 8:
this.$ = procedure($$[$0-2], null, $$[$0]);
break;
case 9:
this.$ = procedure($$[$0-3], $$[$0-2], $$[$0]);
break;
case 10: case 24:
this.$ = $$[$0-1];
break;
case 11:
this.$ = merge($$[$0-2], $$[$0].name);
break;
case 12:
this.$ = $$[$0].name;
break;
case 13: case 27:
this.$ = mkArray($$[$0-1]);
break;
case 14:
this.$ = [];
break;
case 21:
this.$ = conditional($$[$0-3], $$[$0-1], $$[$0]);
break;
case 23:
this.$ = $$[$0];
break;
case 25:
this.$ = invocation($$[$0-1], null, _$[$0-1].first_line);
break;
case 26:
this.$ = invocation($$[$0-2], $$[$0-1],   _$[$0-2].first_line);
break;
case 28:
this.$ = merge($$[$0-2], $$[$0]);
break;
case 30:
this.$ = argument($$[$0-2], $$[$0]);
break;
case 31:
this.$ = repeat(mkArray($$[$0-2]), $$[$0]);
break;
case 34:
this.$ = addition($$[$0-2], $$[$0]);
break;
case 35:
this.$ = subtraction($$[$0-2], $$[$0]);
break;
case 38:
this.$ = action($$[$0], _$[$0].first_line);
break;
case 39:
this.$ = condition($$[$0], _$[$0].first_line);
break;
case 40:
this.$ = condition($$[$0], _$[$0].first_line, true);
break;
case 41:
this.$ = identifier($$[$0]);
break;
case 42:
this.$ = numeric($$[$0]);
break;
}
},
table: [{3:1,4:2,6:4,7:3,8:$V0,9:6,47:$V1},{1:[3]},{5:[1,8],6:9,7:10,8:$V0,9:6,47:$V1},{6:11,8:$V2,9:6,47:$V1},o($V3,[2,5]),o($V4,[2,7]),{10:[1,13],12:14,13:[1,15]},o([10,13,15,16,19,25,30,32,33,34,41,42,44],[2,41]),{1:[2,1]},o($V3,[2,2]),{6:16,8:$V2,9:6,47:$V1},o($V3,[2,4]),o($V4,[2,6]),{11:17,17:$V5},{10:[1,19]},{9:21,14:20,47:$V1},o($V3,[2,3]),o($V3,[2,8]),{18:22,19:[1,23],20:24,21:25,22:26,23:27,24:28,25:$V6,30:$V7,33:$V8,44:$V9},{11:33,17:$V5},{15:[1,34],16:[1,35]},o($Va,[2,12]),{19:[1,36],20:37,21:25,22:26,23:27,24:28,25:$V6,30:$V7,33:$V8,44:$V9},o($Vb,[2,14]),o($Vc,[2,16]),o($Vc,[2,17]),o($Vc,[2,18]),o($Vc,[2,19]),o($Vc,[2,20]),{26:38,30:[1,39]},{9:40,47:$V1},{18:41,20:24,21:25,22:26,23:27,24:28,25:$V6,30:$V7,33:$V8,44:$V9},o($Vc,[2,38]),o($V3,[2,9]),{10:[2,10]},{9:42,47:$V1},o($Vb,[2,13]),o($Vc,[2,15]),{27:[1,43]},{31:44,45:[1,45],46:[1,46]},{13:[1,49],34:[1,47],35:48},{20:37,21:25,22:26,23:27,24:28,25:$V6,30:$V7,32:[1,50],33:$V8,44:$V9},o($Va,[2,11]),{11:51,17:$V5},{32:[1,52]},{32:[2,39]},{45:[1,53]},o($Vc,[2,25]),{34:[1,54]},{9:57,36:55,37:56,47:$V1},{9:61,38:59,39:58,40:60,43:62,47:$V1,48:$Vd},o($Vc,[2,22],{28:64,29:[1,65]}),{27:[2,24]},{32:[2,40]},o($Vc,[2,26]),{15:[1,66],16:[1,67]},o($Va,[2,29]),{10:[1,68]},o($Vc,[2,31]),o($Vc,[2,32],{41:$Ve,42:$Vf}),o($Vg,[2,33]),o($Vg,[2,36]),o($Vg,[2,37]),o($Vg,[2,42]),o($Vc,[2,21]),{11:71,17:$V5},{34:[2,27]},{9:57,37:72,47:$V1},{9:61,38:73,40:60,43:62,47:$V1,48:$Vd},{9:61,38:74,40:60,43:62,47:$V1,48:$Vd},{9:61,38:75,40:60,43:62,47:$V1,48:$Vd},o($Vc,[2,23]),o($Va,[2,28]),o($Va,[2,30],{41:$Ve,42:$Vf}),o($Vh,[2,34],{41:$Ve,42:$Vf}),o($Vh,[2,35],{41:$Ve,42:$Vf})],
defaultActions: {8:[2,1],34:[2,10],45:[2,39],52:[2,24],53:[2,40],66:[2,27]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        function _parseError (msg, hash) {
            this.message = msg;
            this.hash = hash;
        }
        _parseError.prototype = Error;

        throw new _parseError(str, hash);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};


    function merge(a, b) {
        if (!Array.isArray(a)) {
            a = [a];
        }
        a.push(b);
        return a;
    }
    function mkArray(a) {
        if (!Array.isArray(a)) {
            a = [a];
        }
        return a;
    }
    function identifier(name) {
        return {
            TYPE: 'IDENTIFIER',
            name: name
        };
    }
    function numeric(value) {
        return {
            TYPE: 'NUMERIC',
            value: value
        };
    }
    function action(name, line) {
        return {
            TYPE: 'ACTION',
            name: name,
            line: line
        };
    }
    function condition(name, line, negate) {
        instance =  {
            name: name,
            line: line
        };
        if(negate){instance.negate = true;}
        return instance;
    }
    function addition(left, right) {
        return {
            TYPE:  'ADD',
            left:  left,
            right: right            
        };
    }
    function subtraction(left, right) {
        return {
            TYPE:  'SUB',
            left:  left,
            right: right
        };
    }
    function argument(identifier, value) {
        return {
            name:  identifier.name,
            value: value
        };
    }
    function invocation(identifier, args, line) {
        return {
            TYPE: 'INVOCATION',
            name: identifier.name,
            args: args,
            line: line
        };
    }
    function add_comments(procedure, comments) {
        procedure.comments = comments;
        return procedure;
    }
    function procedure(identifier, params, statements) {
        instance = {
            TYPE: 'PROCEDURE',
            name: identifier.name,
            statements: statements
        };
        if(params){instance.params = mkArray(params);}
        return instance;
    }
    function conditional(condition, positive, negative) {
        instance = {
            TYPE: 'CONDITIONAL',
            condition: condition.name,
            line: condition.line,
            positive: positive
        };
        if(negative){instance.negative = negative;}
        if(condition.negate){instance.negate = true;}
        return instance;
    }
    function repeat(statements, index) {
        return {
            TYPE: 'REPEAT',
            index: index,
            statements: statements
        };
    }
    function param(name) {
        return {
            name: name
        };
    }


/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:return 8
break;
case 1:/* skip whitespace */
break;
case 2:return 25
break;
case 3:return 27
break;
case 4:return 29
break;
case 5:return 17
break;
case 6:return 19
break;
case 7:return 46
break;
case 8:return 45
break;
case 9:return 44
break;
case 10:return 'expression'
break;
case 11:return 10
break;
case 12:return 13
break;
case 13:return 15
break;
case 14:return 33
break;
case 15:return 34
break;
case 16:return 30
break;
case 17:return 32
break;
case 18:return 16
break;
case 19:return 41
break;
case 20:return 42
break;
case 21:return 48
break;
case 22:return 47
break;
case 23:return 5
break;
case 24:return 'INVALID'
break;
}
},
rules: [/^(?:(#|\*)[^\n]*\n)/,/^(?:\s+)/,/^(?:Si\b)/,/^(?:Entonces\b)/,/^(?:Sino\b)/,/^(?:Inicio\b)/,/^(?:Fin\b)/,/^(?:no\b)/,/^(?:estaPintadoDeNegro(?!\w)|estaPintadoDeVerde(?!\w)|estaPintadoDeRojo(?!\w)|estaPintado(?!\w)|puedoMoverNorte(?!\w)|puedoMoverSur(?!\w)|puedoMoverOeste(?!\w)|puedoMoverEste(?!\w)|puedoMoverDerecha(?!\w)|puedoMoverAbajo(?!\w)|puedoMoverArriba(?!\w)|puedoMoverIzquierda(?!\w))/,/^(?:Arriba(?!\w)|Abajo(?!\w)|Izquierda(?!\w)|Derecha(?!\w)|MoverNorte(?!\w)|MoverSur(?!\w)|MoverOeste(?!\w)|MoverEste(?!\w)|Despintar(?!\w)|PintarNegro(?!\w)|PintarRojo(?!\w)|PintarVerde(?!\w))/,/^(?:expression\b)/,/^(?::)/,/^(?:\{)/,/^(?:\})/,/^(?:\[)/,/^(?:\])/,/^(?:\()/,/^(?:\))/,/^(?:,)/,/^(?:\+)/,/^(?:-)/,/^(?:[0-9]+)/,/^(?:[a-zA-Z]+)/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = elementos;
exports.Parser = elementos.Parser;
exports.parse = function () { return elementos.parse.apply(elementos, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}