/* parser generated by jison 0.4.17 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var elementos = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,5],$V1=[5,44],$V2=[1,12],$V3=[1,23],$V4=[1,25],$V5=[1,24],$V6=[1,26],$V7=[13,14],$V8=[5,17,23,27,28,30,31,42,44],$V9=[17,23,28,30,31,42],$Va=[1,55],$Vb=[1,61],$Vc=[1,62],$Vd=[13,14,17,23,28,30,31,39,40,42],$Ve=[13,14,17,23,28,30,31,42];
var parser = {trace: function trace() { },
yy: {},
symbols_: {"error":2,"start":3,"procedures":4,"EOF":5,"procedure":6,"identifier":7,":":8,"block":9,"params":10,"{":11,"paramNames":12,"}":13,",":14,"Inicio":15,"statements":16,"Fin":17,"statement":18,"conditional":19,"invocation":20,"repeat":21,"action":22,"Si":23,"ifCond":24,"Entonces":25,"optElse":26,"Sino":27,"(":28,"condition":29,")":30,"[":31,"]":32,"arguments":33,"argNames":34,"argName":35,"aritmetic":36,"rIndex":37,"literal":38,"+":39,"-":40,"numeric":41,"ACTION":42,"condicion":43,"IDENTIFIER":44,"NUMERIC":45,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",8:":",11:"{",13:"}",14:",",15:"Inicio",17:"Fin",23:"Si",25:"Entonces",27:"Sino",28:"(",30:")",31:"[",32:"]",39:"+",40:"-",42:"ACTION",43:"condicion",44:"IDENTIFIER",45:"NUMERIC"},
productions_: [0,[3,2],[4,2],[4,1],[6,3],[6,4],[10,3],[12,3],[12,1],[9,3],[9,2],[16,2],[16,1],[18,1],[18,1],[18,1],[18,1],[19,5],[26,0],[26,2],[24,3],[20,3],[20,4],[33,3],[34,3],[34,1],[35,3],[21,4],[37,1],[36,1],[36,3],[36,3],[38,1],[38,1],[22,1],[29,1],[7,1],[41,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
return mkArray($$[$0-1]);
break;
case 2: case 11:
this.$ = merge($$[$0-1], $$[$0]);
break;
case 4:
this.$ = procedure($$[$0-2], null, $$[$0]);
break;
case 5:
this.$ = procedure($$[$0-3], $$[$0-2], $$[$0]);
break;
case 6: case 20:
this.$ = $$[$0-1];
break;
case 7:
this.$ = merge($$[$0-2], $$[$0].name);
break;
case 8:
this.$ = $$[$0].name;
break;
case 9: case 23:
this.$ = mkArray($$[$0-1]);
break;
case 10:
this.$ = [];
break;
case 17:
this.$ = conditional($$[$0-3], $$[$0-1], $$[$0]);
break;
case 19:
this.$ = $$[$0];
break;
case 21:
this.$ = invocation($$[$0-1], null, _$[$0-1].first_line);
break;
case 22:
this.$ = invocation($$[$0-2], $$[$0-1],   _$[$0-2].first_line);
break;
case 24:
this.$ = merge($$[$0-2], $$[$0]);
break;
case 26:
this.$ = argument($$[$0-2], $$[$0]);
break;
case 27:
this.$ = repeat(mkArray($$[$0-2]), $$[$0]);
break;
case 30:
this.$ = addition($$[$0-2], $$[$0]);
break;
case 31:
this.$ = subtraction($$[$0-2], $$[$0]);
break;
case 34:
this.$ = action($$[$0], _$[$0].first_line);
break;
case 35:
this.$ = condition($$[$0], _$[$0].first_line);
break;
case 36:
this.$ = identifier($$[$0]);
break;
case 37:
this.$ = numeric($$[$0]);
break;
}
},
table: [{3:1,4:2,6:3,7:4,44:$V0},{1:[3]},{5:[1,6],6:7,7:4,44:$V0},o($V1,[2,3]),{8:[1,8],10:9,11:[1,10]},o([8,11,13,14,17,23,28,30,31,32,39,40,42],[2,36]),{1:[2,1]},o($V1,[2,2]),{9:11,15:$V2},{8:[1,13]},{7:15,12:14,44:$V0},o($V1,[2,4]),{16:16,17:[1,17],18:18,19:19,20:20,21:21,22:22,23:$V3,28:$V4,31:$V5,42:$V6},{9:27,15:$V2},{13:[1,28],14:[1,29]},o($V7,[2,8]),{17:[1,30],18:31,19:19,20:20,21:21,22:22,23:$V3,28:$V4,31:$V5,42:$V6},o($V8,[2,10]),o($V9,[2,12]),o($V9,[2,13]),o($V9,[2,14]),o($V9,[2,15]),o($V9,[2,16]),{24:32,28:[1,33]},{7:34,44:$V0},{16:35,18:18,19:19,20:20,21:21,22:22,23:$V3,28:$V4,31:$V5,42:$V6},o($V9,[2,34]),o($V1,[2,5]),{8:[2,6]},{7:36,44:$V0},o($V8,[2,9]),o($V9,[2,11]),{25:[1,37]},{29:38,43:[1,39]},{11:[1,42],32:[1,40],33:41},{18:31,19:19,20:20,21:21,22:22,23:$V3,28:$V4,30:[1,43],31:$V5,42:$V6},o($V7,[2,7]),{9:44,15:$V2},{30:[1,45]},{30:[2,35]},o($V9,[2,21]),{32:[1,46]},{7:49,34:47,35:48,44:$V0},{7:53,36:51,37:50,38:52,41:54,44:$V0,45:$Va},o($V9,[2,18],{26:56,27:[1,57]}),{25:[2,20]},o($V9,[2,22]),{13:[1,58],14:[1,59]},o($V7,[2,25]),{8:[1,60]},o($V9,[2,27]),o($V9,[2,28],{39:$Vb,40:$Vc}),o($Vd,[2,29]),o($Vd,[2,32]),o($Vd,[2,33]),o($Vd,[2,37]),o($V9,[2,17]),{9:63,15:$V2},{32:[2,23]},{7:49,35:64,44:$V0},{7:53,36:65,38:52,41:54,44:$V0,45:$Va},{7:53,36:66,38:52,41:54,44:$V0,45:$Va},{7:53,36:67,38:52,41:54,44:$V0,45:$Va},o($V9,[2,19]),o($V7,[2,24]),o($V7,[2,26],{39:$Vb,40:$Vc}),o($Ve,[2,30],{39:$Vb,40:$Vc}),o($Ve,[2,31],{39:$Vb,40:$Vc})],
defaultActions: {6:[2,1],28:[2,6],39:[2,35],45:[2,20],58:[2,23]},
parseError: function parseError(str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        function _parseError (msg, hash) {
            this.message = msg;
            this.hash = hash;
        }
        _parseError.prototype = Error;

        throw new _parseError(str, hash);
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};


    function merge(a, b) {
        if (!Array.isArray(a)) {
            a = [a];
        }
        a.push(b);
        return a;
    }
    function mkArray(a) {
        if (!Array.isArray(a)) {
            a = [a];
        }
        return a;
    }
    function identifier(name) {
        return {
            TYPE: 'IDENTIFIER',
            name: name
        };
    }
    function numeric(value) {
        return {
            TYPE: 'NUMERIC',
            value: value
        };
    }
    function action(name, line) {
        return {
            TYPE: 'ACTION',
            name: name,
            line: line
        };
    }
    function condition(name, line) {
        return {
            name: name,
            line: line
        };
    }
    function addition(left, right) {
        return {
            TYPE:  'ADD',
            left:  left,
            right: right            
        };
    }
    function subtraction(left, right) {
        return {
            TYPE:  'SUB',
            left:  left,
            right: right
        };
    }
    function argument(identifier, value) {
        return {
            name:  identifier.name,
            value: value
        };
    }
    function invocation(identifier, args, line) {
        return {
            TYPE: 'INVOCATION',
            name: identifier.name,
            args: args,
            line: line
        };
    }
    function procedure(identifier, params, statements) {
        instance = {
            TYPE: 'PROCEDURE',
            name: identifier.name,
            statements: statements
        };
        if(params){instance.params = mkArray(params);}
        return instance;
    }
    function conditional(condition, positive, negative) {
        instance = {
            TYPE: 'CONDITIONAL',
            condition: condition.name,
            line: condition.line,
            positive: positive
        };
        if(negative){instance.negative = negative;}
        return instance;
    }
    function repeat(statements, index) {
        return {
            TYPE: 'REPEAT',
            index: index,
            statements: statements
        };
    }
    function param(name) {
        return {
            name: name
        };
    }


/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function (match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex() {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin(condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState() {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules() {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState(n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState(condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip whitespace */
break;
case 1:return 23
break;
case 2:return 25
break;
case 3:return 27
break;
case 4:return 15
break;
case 5:return 17
break;
case 6:return 43
break;
case 7:return 42
break;
case 8:return 'expression'
break;
case 9:return 8
break;
case 10:return 11
break;
case 11:return 13
break;
case 12:return 31
break;
case 13:return 32
break;
case 14:return 28
break;
case 15:return 30
break;
case 16:return 14
break;
case 17:return 39
break;
case 18:return 40
break;
case 19:return 45
break;
case 20:return 44
break;
case 21:return 5
break;
case 22:return 'INVALID'
break;
}
},
rules: [/^(?:\s+)/,/^(?:Si\b)/,/^(?:Entonces\b)/,/^(?:Sino\b)/,/^(?:Inicio\b)/,/^(?:Fin\b)/,/^(?:tieneColorNegro|tieneColorVerde|tieneColorRojo|puedoMoverNorte|puedoMoverSur|puedoMoverOeste|puedoMoverEste|puedoMoverDerecha|puedoMoverAbajo|puedoMoverArriba|puedoMoverIzquierda\b)/,/^(?:Arriba|Abajo|Izquierda|Derecha|MoverNorte|MoverSur|MoverOeste|MoverEste|PintarNegro|PintarRojo|PintarVerde\b)/,/^(?:expression\b)/,/^(?::)/,/^(?:\{)/,/^(?:\})/,/^(?:\[)/,/^(?:\])/,/^(?:\()/,/^(?:\))/,/^(?:,)/,/^(?:\+)/,/^(?:-)/,/^(?:[0-9]+)/,/^(?:[a-zA-Z]+)/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = elementos;
exports.Parser = elementos.Parser;
exports.parse = function () { return elementos.parse.apply(elementos, arguments); };
exports.main = function commonjsMain(args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}